### ISSUE TITLE
TLDS RGBA instruction broken

### ISSUE THREAD

**Issue by andravin** [NervanaSystems/maxas#3]
The TLDS RGBA instruction has been broken since March 4 checkin b744f88d9d00b358ce7446a0724a042b582f04fa

This breaks maxDNN.

The problem is that the following lines were removed from MaxasGrammar.pm:

TLDS: chnls
0x0010000000000000 RGBA

**Comment by scott-gray** [comment]
Sorry about that.  I re-factored your change a bit but missed that part.
No matter how small the change it's always worth testing.. guess I failed
on that one.

Should be all set now.

-Scott

**Comment by andravin** [comment]
Fix works for me, thanks.

I think if there was a coverage test in Maxas that checked the op codes of a bunch of instructions, it would have caught this regression error. Does that sound like a good idea? I seem to recall you used something like that to explore new instructions anyway.

**Comment by scott-gray** [comment]
I did have a bunch of unit tests working, but haven't been good about
keeping that up to date.  I just have way too much on my plate to be able
to fill in all the little details for all my projects that I should be.  If
that's something you want to contribute it would be a big help.  There is
now a team at Alibaba working on a Kepler version and I'm sure they could
make use of the same test framework.  Basically we just need a bunch of ptx
code that exercises all the instructions with all the potential flags
(all.ptx was the start of this).  But ptx is kind of an abomination of a
program language to be working in and hence pretty tedious.  There's also
the challenge of making sure your test code doesn't get optimized away by
ptxas.

-Scott

**Comment by andravin** [comment]
Can't you just disassemble and reassemble a list of cubins? Like start with your lib and maxDNN.
