### ISSUE TITLE
Problems with MOV-instruction and the "enhanced cubin support" commit

### ISSUE THREAD

**Issue by pr0metha** [NervanaSystems/maxas#7]
Hi,

I've encountered two problems. Both are possible to replicate with the microbench application code by extracting the sass code and then trying to insert the unmodified code into the kernel again:

> $ maxas.pl -e microbench.cubin microbench.sass
> $ maxas.pl -i microbench.sass microbench.cubin
1. When doing the insertion step, I get this: 
   Unable to encode instruction: MOV R1, c[0x0];

It seems like something goes wrong in the extraction step here, because the second argument should have two address fields. This is what nvdisasm returns:  MOV R1, c[0x0][0x20];
The error is removed by adding [0x20]. 

I've seen this problem in all kernels I've been trying to insert after extracting them with maxas.
1. After modifying the MOV-instruction, this is the output from the insertion step:

Unknown Code 0x10 (size:0)

Unknown Code 0x18 (size:0)

Unknown Code 0x00 (size:0)

Unknown Code 0x00 (size:0)

Modified microbench CTAID Offsets: '' => '0018,0028'

Modified microbench Exit Offsets: '00e8,0000,0000' => '0138'

Modified microbench ParamSecSize: 100 => 88

Kernel: microbench, Instructions: 0, Register Count: 10, Bank Conflicts: 0, Reuse: 21.1% (4/19)

It seems strange that all these parameters are modified when the kernel is unchanged. And indeed, when running the application with the modified cubin I get a segmentation fault. I've tried different kernels with the same result. This doesn't happen if I roll back maxas to the commit before the enhanced cubin support was added and try the exact same thing, so I guess something goes wrong when the offsets are modified.

Thanks!

**Comment by scott-gray** [comment]
Thanks, I'll look into this today.

Quick question though, are you using the nvdiasasm from cuda 6.5?  The
later versions are not compatible with maxas (the rest of cuda is, you just
need to overwrite the new version of nvdiasasm from the 6.5 release).

**Comment by scott-gray** [comment]
Ok, submitted a fix.  Let me know if that addresses your problems.

**Comment by pr0metha** [comment]
The MOV instruction problem is now eliminated. Thanks!

I was using the entire cuda-6.5 package. When doing that, the second problem still persists. However, if changing to cuda-7.5 with the 6.5-version of nvdisasm, everything works as expected. So I guess the second issue is not really an issue as long as no one uses cuda-6.5 (other than nvdisasm of course). :)

**Comment by scott-gray** [comment]
Yah, nvidia keeps making minor tweaks I need to adjust to.  The new nvdisasm thing actually looks like a bug in that it outputs a bunch of useless and spurious brace characters into the assembly.
